Fix uninitialized value warning: `cover -write``
pjcj/Devel--Cover pull request #339
Opened 2024-07-15 05:54 UTC by jsoref

fixes #317

Introduced by ea35cf06f52f25e0c681ae488b8fa6d498f9d48f

2024-07-21 19:19 UTC, pjcj commented
Thanks for tracking down and fixing this.

2024-12-08 15:03 UTC, pjcj requested changes
Sorry, I obviously have no idea how to drive github.  I thought I had made a comment here but apparently it was in a pending state.

2024-12-08 16:24 UTC, jsoref commented on bin/cover
> +    my $format = "Devel::Cover::Report::\u$report" if $report;
You might not know how to drive GitHub, but you trigger a bug in GitHub mobile which shows your comment as having been made 5 months ago!
https://github.com/orgs/community/discussions/146598

2025-05-04 10:26 UTC, pjcj commented
Thanks for this!  I've rearranged the file a little since you created this PR so I've implemented a conceptually similar change and it will be in the next release.

2025-05-04 10:26 UTC, closed without merging